theme: jekyll-theme-cayman
title: Instalando e Tentando o serviço CGI
description: Este projeto visa a instalação e a visualização do serviço CGI utilizando a linguagem python para escrever os sites web
